### ISSUE TITLE
Consider disabling calculated read/write capacity alarms for on demand tables

### ISSUE THREAD

**Issue by tomhaigh** [justeat/AwsWatchman#263]
The alarms currently fire on any usage of the table because the provisioned capacity can be zero.

**Comment by tomhaigh** [comment]
If we wanted to do this would have to make it work across new and old implementations. The latter is harder because alarms are not currently deleted, so you might want to update to a very high threshold instead as a simple fix.

**Comment by Simon-Bull** [comment]
@tomhaigh I think this mitigates this issue: https://github.com/justeat/AwsWatchman/pull/26
